name: Run Cypress tests

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Select the spec file to run tests'
        type: choice
        options:
          - cypress/e2e/01-main.spec.cy.ts
          - cypress/e2e/02-dronjo-simple.spec.cy.ts
          - cypress/e2e/03-dronjo-advanced.spec.cy.ts
        required: true
        default: cypress/e2e/01-main.spec.cy.ts

jobs:
    configure:
        runs-on: ubuntu-latest
        outputs:
            uid_gid: ${{ env.UID_GID }}
        steps:
          - id: get-user
            run: echo "UID_GID=$(id -u):$(id -g)" >> $GITHUB_ENV

    test:
        runs-on: ubuntu-latest
        needs: configure
        container: 
            image: ghcr.io/wopee-io/runtime
            options: --user ${{ needs.configure.outputs.uid_gid }}

        steps:
          - uses: actions/checkout@v4

          - name: Run tests
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WOPEE_API_KEY: ${{ secrets.WOPEE_API_KEY }}
                WOPEE_API_URL: ${{ vars.WOPEE_API_URL || 'https://api.wopee.io' }}
                WOPEE_PROJECT_UUID: ${{ vars.WOPEE_PROJECT_UUID }}
                WOPEE_PROJECT_URL: ${{ vars.WOPEE_PROJECT_URL || 'https://dronjo.wopee.io' }}
                # WOPEE_SCREENSHOT_VALIDATION_ENABLED: "true"
                # WOPEE_BRANCH_NAME: master
                # WOPEE_CI_BUILD_ID: build-123
                # WOPEE_CUSTOM_TAGS: custom-tag
                # WOPEE_ENABLE_SOFT_ASSERT: "true"
                # WOPEE_PIXEL_TO_PIXEL_DIFF_TOLERANCE: "0.1"
            run: npm run cy -- --spec ${{ github.event.inputs.spec }}
